FROM jenkins/jenkins:lts

USER root

RUN apt-get update && apt-get install -y \
    docker.io \
    make \
    g++ \
    curl

RUN groupmod -g 1001 docker || groupadd -g 1001 docker
RUN usermod -aG docker jenkins

USER jenkins